import type { Metadata } from "next";
import { montserrat, playfairDisplay } from "./ui/fonts";
import "./globals.css";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={playfairDisplay.className}>
        <nav className="fixed w-full top-0 left-0 justify-center items-center flex z-50 h-20 bg-transparent">
          <div className="flex w-full max-w-screen-lg justify-center px-4">
            <Image src="/barbershop.png" alt="barber" width={200} height={50} />
          </div>        
        </nav>
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
