import type { Metadata } from "next";
import { montserrat } from "./ui/fonts";
import "./globals.css";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <nav className="flex justify-center items-center h-16 bg-black">
          <Image src="/barbershop.png" alt="barber" width={150} height={50} />
        </nav>
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
